version: '3'

services:
  web:
    container_name: g2_app
    build:
      context: .
      dockerfile: ./dockers/rails/Dockerfile
    image: g2_app-rails:3.2
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
    environment:
      NOTHING: "NOTHING"
      REDIS_URL: redis://redis:6379/1
    command: >
      bash -c "rm /app/tmp/pids/server.pid; bundle && yarn && bundle exec rails db:migrate && PROCFILE=procfile.dev bin/dev"
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    networks:
      - net
  redis:
    image: "redis:alpine"
    networks:
      - net

volumes:
  bundle_data:

networks:
  net:
